#! /bin/sh

# Launch a daemon w/ arguments if it's not already running
function startd {
  pgrep -x $1 > /dev/null || $1 ${@:2} &
}

startd sxhkd

# Compositor
startd picom -bc --backend glx --vsync

# Notification manager
startd dunst

# Battery notifications
startd batsignal -w 20 -c 10 -d 5 -I /usr/share/icons/Papirus/128x128/devices/battery.svg -b

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

bspc config pointer_modifier shift

# $XDG_CONFIG_HOME/WALLPAPER should be a symlink to the default wallpaper
feh --bg-scale $XDG_CONFIG_HOME/WALLPAPER
