# From https://draculatheme.com/fuzzel
[main]
show-actions=yes
width=60
[colors]
background=282a36dd
text=f8f8f2ff
match=8be9fdff
selection-match=8be9fdff
selection=44475add
selection-text=f8f8f2ff
border=bd93f9ff
[key-bindings]
# Custom bindings select the chosen program but return unique error codes
custom-1=Control+Return
# 'Mod1' is Alt
custom-2=Mod1+Return
